BASE_URL = "https://www.saucedemo.com/"
username_id = "user-name"
password_id = "password"
login_button_id = "login-button"
errorMessage_xpath1 = "//*[@id='login_button_container']/div/form/div[3]/h3"
expectedMessage1_text = "Epic sadface: Username is required"
expectedMessage2_text = "Epic sadface: Password is required"
expectedMessage2_xpath = "//*[@id='login_button_container']/div/form/div[3]"
expectedMessage3_text = "Epic sadface: Sorry, this user has been locked out."
errorMessage_text = "Epic sadface: Username and password do not match any user in this service" 
mesaj = "şeklinde uyarı mesajı gösterilmiştir"
first_name_id = "first-name"
last_name_id = "last-name"
zip_code_id = "postal-code"
continue_button_id = "continue"
finish_button_id = "finish"
dropDown_class_name="product_sort_container"
baslik_xpath = "//*[@id='header_container']/div[1]/div[2]/div"
baslik_class_name = "complete-header"
baslik2_text= "Thank you for your order!"
baslik1_text = "Swag Labs"
firstName_id = "first-name"
lastName_id = "last-name"
postalCode_id = "postal-code"
continueBtn_id = "continue"
finish_id = "finish"
dropDown_class_name="product_sort_container"
baslik_xpath = "//*[@id='header_container']/div[1]/div[2]/div"
baslik_class_name = "complete-header"
baslik_text1 = "Thank you for your order!"
baslik_text2 = "Swag Labs"
checkout_id = "checkout"
secme_class_name = "product_sort_container"
standard_user = "standard_user"
secret_sauce = "secret_sauce"
bir = "bir"
locket_out = "locked_out_user"
sepet_class_name = "shopping_cart_link"
urunEkle1_xpath = "//*[@id='add-to-cart-test.allthethings()-t-shirt-(red)']"
urunEkle2_xpath = "//*[@id='add-to-cart-sauce-labs-onesie']"
remove_button_xpath = "//*[@id='remove-test.allthethings()-t-shirt-(red)']"
urunEkle_xpath = "//*[@id='add-to-cart-test.allthethings()-t-shirt-(red)']"
urunEkle1_xpath = "//*[@id='add-to-cart-sauce-labs-onesie']"
remove_xpath = "//*[@id='remove-test.allthethings()-t-shirt-(red)']"
menuButton_id = "react-burger-menu-btn"
aboutLink_id = "about_sidebar_link"
