# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestProductslist3():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_productslist3(self):
    self.driver.get("https://www.saucedemo.com/")
    self.driver.maximize_window()
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.ID, "user-name")))
    self.driver.find_element(By.ID, "user-name").send_keys("standard_user")
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.ID, "password")))
    self.driver.find_element(By.ID, "password").send_keys("secret_sauce")
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.ID, "login-button")))
    self.driver.find_element(By.ID, "login-button").click()
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.ID, "add-to-cart-test.allthethings()-t-shirt-(red)")))
    self.driver.find_element(By.ID, "add-to-cart-test.allthethings()-t-shirt-(red)").click()
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.ID, "add-to-cart-sauce-labs-onesie")))
    self.driver.find_element(By.ID, "add-to-cart-sauce-labs-onesie").click()
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.XPATH, "//div[@id=\'shopping_cart_container\']/a")))
    self.driver.find_element(By.XPATH, "//div[@id=\'shopping_cart_container\']/a/span").click()
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.ID, "remove-test.allthethings()-t-shirt-(red)")))
    self.driver.find_element(By.ID, "remove-test.allthethings()-t-shirt-(red)").click()
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.ID, "checkout")))
    self.driver.find_element(By.ID, "checkout").click()
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.ID, "first-name")))
    self.driver.find_element(By.ID, "first-name").send_keys("Muhsine ")
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.ID, "last-name")))
    self.driver.find_element(By.ID, "last-name").send_keys("Taşcı")
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.ID, "postal-code")))
    self.driver.find_element(By.ID, "postal-code").send_keys("123456")
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.ID, "continue")))
    self.driver.find_element(By.ID, "continue").click()
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.ID, "finish")))
    self.driver.find_element(By.ID, "finish").click()
    WebDriverWait(self.driver, 5).until(expected_conditions.visibility_of_element_located((By.XPATH, "//div[@id=\'checkout_complete_container\']/h2")))
    # Baslik
    assert self.driver.title == "Swag Labs"
  
